### ISSUE TITLE
Issue when using river with postgresql jdbc 

### ISSUE THREAD

**Issue by anuhabi** [jprante/elasticsearch-river-jdbc#426]
Hi,
i liked your plugin. it work fine with mysql for most of the use cases. 
1) I'm encountering an issue when i created a river using postgresql jdbc to connect Greenplum.
2) When i try to create a feeder with same driver i get class not found exception

Log Message
------------------
[vddu-pdi-cent4] [2014-12-22 16:36:32,426][INFO ][index.shard.service      ] [PDIES-Pasta-N4] [pdi-simpleindex][4] updating refresh_interval from [-1000] to [1s]
**[vddu-pdi-cent4] [2014-12-22 16:36:32,440][ERROR][river.jdbc.RiverPipeline ] java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Statement.setQueryTimeout(int) is not yet implemented.
[vddu-pdi-cent4] java.io.IOException: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Statement.setQueryTimeout(int) is not yet implemented.
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:341)
**[vddu-pdi-cent4] 	at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.fetch(SimpleRiverFlow.java:209)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.execute(SimpleRiverFlow.java:139)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.request(RiverPipeline.java:88)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:66)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:30)
[vddu-pdi-cent4] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[vddu-pdi-cent4] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[vddu-pdi-cent4] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[vddu-pdi-cent4] 	at java.lang.Thread.run(Thread.java:745)
[vddu-pdi-cent4] Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Statement.setQueryTimeout(int) is not yet implemented.
[vddu-pdi-cent4] 	at org.postgresql.Driver.notImplemented(Driver.java:751)
[vddu-pdi-cent4] 	at org.postgresql.jdbc2.AbstractJdbc2Statement.setQueryTimeout(AbstractJdbc2Statement.java:666)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.execute(SimpleRiverSource.java:380)
[vddu-pdi-cent4] 	at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:320)
[vddu-pdi-cent4] 	... 9 more
[vddu-pdi-cent4] [2014-12-22 16:36:32,441][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@33f037dd complete: river jdbc/my_jdbc_river_test metrics: 0 rows, 0.0 mean, (0.0 0.0 0.0), ingest metrics: elapsed 0 seconds, 0.0 bytes bytes, 0.0 bytes avg, 0 MB/s

-------

JDBC Plugin Version: 1.4.0.3.Beta1 installed in all the nodes.
Postgres JDBC Driver: 9.1-903 JDBC 4 and tried other versions as well.
ES: 1.4.1
Java: 1.7.0_67
OS: CentOS
Nodes: 5
Masters: 1
Data Nodes: 5

curl -XPOST '10.98.34.27:9200/_river/my_jdbc_river_test/_meta' -d '
{
  "type": "jdbc",
  "jdbc": {
    "driver" : "org.postgresql.Driver",
    "url": "jdbc:postgresql://localhost:5432/warehouse",
    "user": "read_warehousedb",
    "password": "******",
    "sql": "select asupid as uid, sn as uname from asup.geninfo",
    "index": "simpleindex",
    "type": "simpleindex-mapping",
    "index_settings": {
      "index": {
        "number_of_shards": 5
      }
    }
}
}
'

can you shed some light? thank you in advance and appreciate the support.

**Comment by anuhabi** [comment]
Awesome! Thanks much! I will try them.

**Comment by anuhabi** [comment]
Works Well. Thanks a lot.
