### ISSUE TITLE
Message not fully read

### ISSUE THREAD

**Issue by trK54Ylmz** [jprante/elasticsearch-river-jdbc#445]
I got this error every time.

```
$ ls jdbc
```
```
elasticsearch-river-jdbc-1.4.0.8.jar	mysql-connector-java-5.1.33-bin.jar
```
Everything fine but
```
PUT /_river/my_jdbc_river/_meta
{
   "concurrency": 2,
   "type": "jdbc",
   "jdbc": {
      "url": "jdbc:mysql://10.**.**.**:3306/main",
      "user": "test",
      "password": "test123",
      "sql": "select id AS commentId, UNCOMPRESS(comment) comment FROM comments",
      "index": "test",
      "type": "comments"
   }
}
```

```
[2015-01-22 08:38:09,198][WARN ][transport.netty          ] [Franz Kafka] Message not fully read (request) for [9743] and action [org.xbib.elasticsearch.action.river.jdbc.state.get], resetting
[2015-01-22 08:38:09,200][WARN ][river.jdbc.SimpleRiverFlow] no river mouth
[2015-01-22 08:38:09,200][ERROR][river.jdbc.RiverPipeline ] No handler for action [org.xbib.elasticsearch.action.river.jdbc.state.get]
org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [org.xbib.elasticsearch.action.river.jdbc.state.get]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:210)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-01-22 08:38:09,202][ERROR][river.jdbc.RiverThread   ] java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.xbib.elasticsearch.plugin.jdbc.pipeline.executor.SimplePipelineExecutor.waitFor(SimplePipelineExecutor.java:124)
        at org.xbib.elasticsearch.plugin.jdbc.pipeline.executor.MetricSimplePipelineExecutor.waitFor(MetricSimplePipelineExecutor.java:61)
        at org.xbib.elasticsearch.plugin.jdbc.RiverRunnable.run(RiverRunnable.java:123)
        at java.lang.Thread.run(Thread.java:745)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:70)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:30)
        ... 4 more
```

**Comment by jprante** [comment]
You did not install the JDBC plugin on all nodes.

**Comment by rthneha** [comment]
what do you mean by install plugin on all nodes.
I installed plugin under plugins folder. where else it needs to get installed? can you please explain.

**Comment by jprante** [comment]
How many nodes did you set up? Only one?

**Comment by rthneha** [comment]
2 nodes

**Comment by rthneha** [comment]
[root@localhost elasticsearch]# ls
bin  config  data  lib  LICENSE.txt  logs  NOTICE.txt  plugins  README.textile

I have elasticsearch installed in a directory. I installed the plugin under plugins floder.
i.e. mysql-connector-java-5.1.33-bin.jar inside plugin/river-jdbc folder &
elasticsearch-river-jdbc-1.4.0.6.jar inside plugin/jdbc folder

when I hit http://192.168.0.94:9200/_nodes/process?pretty=true
i get below details: seems like it's 1 node only. how can resolve No handler for action exception with this...

{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "cokk0Hs1R6qfiE1cRG5jlA" : {
      "name" : "Ajak",
      "transport_address" : "inet[/192.168.0.94:9300]",
      "host" : "localhost.localdomain",
      "ip" : "127.0.0.1",
      "version" : "1.4.2",
      "build" : "927caff",
      "http_address" : "inet[/192.168.0.94:9200]",
      "process" : {
        "refresh_interval_in_millis" : 1000,
        "id" : 25829,
        "max_file_descriptors" : 4096,
        "mlockall" : false
      }
    }
  }
}

**Comment by rthneha** [comment]
can anyone help for this exception:

[2015-01-30 14:55:40,336][INFO ][cluster.metadata         ] [Rachel van Helsing] [_river] creating index, cause [auto(index api)], shards [1]/[1], mappings []
[2015-01-30 14:55:41,911][INFO ][cluster.metadata         ] [Rachel van Helsing] [_river] update_mapping [admin_log] (dynamic)
[2015-01-30 14:55:41,995][INFO ][river.jdbc.JDBCRiver     ] started river instance for single run
[2015-01-30 14:55:41,999][INFO ][river.jdbc.RiverThread   ] scheduled metrics thread at 60 seconds
[2015-01-30 14:55:42,005][INFO ][river.jdbc.RiverThread   ] scheduled suspend check thread at 1 seconds
[2015-01-30 14:55:42,022][INFO ][cluster.metadata         ] [Rachel van Helsing] [_river] update_mapping [admin_log] (dynamic)
[2015-01-30 14:55:42,065][WARN ][transport.netty          ] [Rachel van Helsing] Message not fully read (request) for [96] and action [org.xbib.elasticsearch.action.river.jdbc.state.get], resetting
[2015-01-30 14:55:42,115][WARN ][river.jdbc.SimpleRiverFlow] no river mouth
[2015-01-30 14:55:42,116][ERROR][river.jdbc.RiverPipeline ] No handler for action [org.xbib.elasticsearch.action.river.jdbc.state.get]
org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [org.xbib.elasticsearch.action.river.jdbc.state.get]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:210)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

I created request with body:

curl -XPUT '192.168.0.94:9200/_river/admin_log/_meta' -d '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://192.168.0.43:3306/trendsutra3",
        "user" : "eadmin",
        "password" : "e@dm!n",
        "sql" : "SELECT * FROM adminlogger_log LIMIT 10"
    }
}'

& I have 2 node cluster. I installed jars inside plugins folder.

**Comment by trK54Ylmz** [comment]
Thank you @jprante 

My problem solved. I had one node but also one more node was run. I didn't noticed, I terminated other elasticsearch node and everything fine now.

**Comment by sroze** [comment]
@jprante Is the ElasticSearch plugin needed in the Feeder case ?

**Comment by jprante** [comment]
@sroze yes, but this was unintended. I work on a persistence state mechanism independent of an ES cluster.

**Comment by sroze** [comment]
@jprante Great, could you ping me here to let my try it ?

**Comment by jprante** [comment]
@sroze sure, I will.
