### ISSUE TITLE
Custom index + type throws error

### ISSUE THREAD

**Issue by einfallstoll** [jprante/elasticsearch-river-jdbc#473]
If I try to create a new river I always get an exception.

**curl command**
```
curl -XPUT 'localhost:9200/_river/psm/_meta' -d '{
    "type": "jdbc",
    "jdbc": {
        "url": "jdbc:oracle:thin:@svrpsm01:1521:psm",
        "user": "sm_ro",
        "password": "sm_ro",
        "sql": "select * from device2m1",
        "index": "psm",
        "type": "devices"
    }
}'
```

**error**
```
[2015-02-24 13:38:25,386][INFO ][cluster.metadata         ] [sm-node-t01] [_river] creating index, cause [auto(index api)], shards [1]/[1], mappings [psm]
[2015-02-24 13:38:25,798][DEBUG][action.index             ] [sm-node-t01] [_river][0], node[LDGgjueiR2uifwxJwxO8og], [P], s[STARTED]: Failed to execute [index {[_river][psm][_meta], source[_na_]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:563)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:189)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent from (offset=0, length=5): [-91, -76, -29, -29, 127]
        at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:195)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:73)
        at org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:51)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:505)
        ... 8 more
[2015-02-24 13:38:29,813][WARN ][river.routing            ] [sm-node-t01] no river _meta document found after 5 attempts

```

Also mentioned here: http://stackoverflow.com/questions/28385265/elasticsearch-oracle-jdbc-river

**Comment by einfallstoll** [comment]
`bulk_size` was missing.

```
curl -XPUT 'localhost:9200/_river/psm/_meta' -d '{
    "type": "jdbc",
    "jdbc": {
        "url": "jdbc:oracle:thin:@svrpsm01:1521:psm",
        "user": "sm_ro",
        "password": "sm_ro",
        "sql": "select * from device2m1",
        "index": "psm",
        "type": "devices",
        "bulk_size": 100
    }
}'
```
