### ISSUE TITLE
After configured with ELK shield, I'm unauthorized to access this plugin resource

### ISSUE THREAD

**Issue by nutts** [jprante/elasticsearch-river-jdbc#498]
this plugin works well, but after I configured ELK shield, I got the following error message, even I modified the JDBCFeeder.java by passing shield.user into setting.

.put("shield.user", "ddtuser:mypassword")  //ddtuser has admin role

[pool-3-thread-1] ERROR river.jdbc.RiverPipeline - action [org.xbib.elasticsearch.action.river.jdbc.state.get] is unauthorized for user [ddtuser]
org.elasticsearch.shield.authz.AuthorizationException: action [org.xbib.elasticsearch.action.river.jdbc.state.get] is unauthorized for user [ddtuser]
	at org.elasticsearch.shield.authz.InternalAuthorizationService.denial(InternalAuthorizationService.java:247)
	at org.elasticsearch.shield.authz.InternalAuthorizationService.authorize(InternalAuthorizationService.java:132)
	at org.elasticsearch.shield.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:72)
	at org.elasticsearch.shield.transport.ShieldServerTransportService$ProfileSecuredRequestHandler.messageReceived(ShieldServerTransportService.java:171)
	at org.elasticsearch.shield.transport.netty.ShieldMessageChannelHandler.handleRequest(ShieldMessageChannelHandler.java:65)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)

**Comment by jprante** [comment]
Shield does not support JDBC plugin.

**Comment by radiumx3** [comment]
Any workaround to this ?

**Comment by jprante** [comment]
Shield is not open source, so I can not support it.

It is possible for Shield programmers to fork JDBC plugin and create a new plugin that works with Shield.

**Comment by d0lur1g** [comment]
Hello jprante,
Exists it an alternative at shield for to keep the authentication and the different autorizations of users?

I wish keep jdbc-river but by using a security system. Essentially with kibana so that I authorize various rights between admin and users. (admin will can edit, save, etc... while users will can only read the dashboards)

My issue on stackoverflow :
http://stackoverflow.com/questions/29675260/alternative-jdbc-river-and-shield

Thanks.

**Comment by floragunncom** [comment]
maybe this is the right for you? https://github.com/floragunncom/search-guard
