### ISSUE TITLE
Seemingly valid type_mapping setting on the river is causing a JSON parsing exception

### ISSUE THREAD

**Issue by sstorie** [jprante/elasticsearch-river-jdbc#506]
I'm trying to import a bunch of log data, but I've got a field that I don't want to have analyzed, so I'm using the JSON below to create my river:

```json
{
    "type":"jdbc",
    "jdbc": {
        "url":"jdbc:sqlserver:/XXXXXXXXXXXXXXX;databaseName=XXXXXXXX",
        "user":"XXXXXXX",
        "password":"XXXXXXXX",
        "sql": "SELECT * FROM software_log (NOLOCK) WHERE log_date > '2015/03/25'",
        "index": "logs",
        "type": "software",
        "type_mapping": {
            "software": {
                "software_name": { "type": "string", "index": "not_analyzed" }
            }
        }
    }
}
```

The problem I'm running into is I can't get the *type_mapping* setting to work no matter what I try. If I exclude it I can import my data just fine, so I know things are working overall. I've tried numerous variations where I try to use "properties" in the *type_mapping* object, passing the JSON as a string value on the *type_mapping* property, but nothing works. The code itself has examples that appear to be set up exactly like what I have above:

https://github.com/jprante/elasticsearch-river-jdbc/blob/e13884c0142ffe5e4f755fb6c427e0ca895a9bde/src/test/resources/org/xbib/elasticsearch/river/jdbc/strategy/simple/hsqldb/river-3.json

...but it just doesn't work for me. The JSON above generates this error in my elasticsearch log too (note the line around the middle that indicates a JSON parsing issue is what's happening):

```
[2015-03-25 11:28:10,983][DEBUG][action.admin.indices.mapping.put] [Ringmaster] failed to put mappings on indices [[logs]], type [software]
org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:128)
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:105)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:184)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:434)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:365)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Unexpected character ('=' (code 61)): was expecting a colon to separate field name and value
 at [Source: org.elasticsearch.common.compress.lzf.LZFCompressedStreamInput@491c9a96; line: 1, column: 11]
	at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._skipColon2(UTF8StreamJsonParser.java:2759)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._skipColon(UTF8StreamJsonParser.java:2734)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:51)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:268)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readOrderedMap(AbstractXContentParser.java:258)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:213)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrderedAndClose(AbstractXContentParser.java:228)
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:123)
	... 10 more

```

So somewhere invalid JSON is being created and passed along, but I'm at a loss for where to turn next. Is there a clear guide on how to specify custom mappings when creating rivers? Or even better, what I'm doing wrong here?

**Comment by jprante** [comment]
Are you using Elasticsearch 1.4+?

**Comment by sstorie** [comment]
Yes, I'm using the 1.5 version.

**Comment by jprante** [comment]
Please try

```
{
    "type":"jdbc",
    "jdbc": {
        "url":"jdbc:sqlserver:/XXXXXXXXXXXXXXX;databaseName=XXXXXXXX",
        "user":"XXXXXXX",
        "password":"XXXXXXXX",
        "sql": "SELECT * FROM software_log (NOLOCK) WHERE log_date > '2015/03/25'",
        "index": "logs",
        "type": "software",
        "type_mapping": {
            "software": {
                "properties" : {
                    "software_name": { "type": "string", "index": "not_analyzed" }
                }
            }
        }
    }
}
```

**Comment by sstorie** [comment]
Yeah, that doesn't work either, and results in the same parsing error:

```
[2015-03-25 16:14:47,223][DEBUG][action.admin.indices.mapping.put] [Reignfire] failed to put mappings on indices [[logs]], type [software]
org.elasticsearch.ElasticsearchParseException: Failed to parse content to map
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:128)
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:105)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:184)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:434)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:365)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Unexpected character ('=' (code 61)): was expecting a colon to separate field name and value
 at [Source: org.elasticsearch.common.compress.lzf.LZFCompressedStreamInput@4ac4c3dd; line: 1, column: 11]
	at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._skipColon2(UTF8StreamJsonParser.java:2759)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._skipColon(UTF8StreamJsonParser.java:2734)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:51)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:268)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readOrderedMap(AbstractXContentParser.java:258)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:213)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrderedAndClose(AbstractXContentParser.java:228)
	at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:123)
	... 10 more
```

**Comment by jprante** [comment]
Are you sure you pass correct JSON? You seem to have a `=` character somewhere.

This works here

```
#!/bin/sh

curl -XPUT '0:9200/_river/my_mysql_river/_meta' -d '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/test",
        "user" : "",
        "password" : "",
        "sql" :  "select *, created as _id from orders",
        "index": "logs",
        "type": "software",
        "type_mapping": {
            "software": {
                "properties" : {
                    "software_name": { "type": "string", "index": "not_analyzed" }
                }
            }
        }
    }
}'
```

**Comment by sstorie** [comment]
Hrm, I appreciate the help but I can't see what I'm doing wrong here. I modified the JSON to remove any '=' character at all, even though the only one was in the connection string, and still get the parsing error. I have been using postman (on windows), but I also tried Elastic's Sense tool to send the JSON, and get the same result. I don't have curl installed on my windows laptop, but perhaps I should try that next.

What's strange to me is I get what appears to be a valid response back from ElasticSearch:

```
{
   "_index": "_river",
   "_type": "software_log_river",
   "_id": "_meta",
   "_version": 1,
   "created": true
}
```
The only indication that something is wrong is the errors that get dumped into the log. I'll keep digging, but at least I know what the JSON *should* look like now :)

**Comment by jprante** [comment]
Try in Sense

```
DELETE /_river/my_jdbc_river/
DELETE /logs
PUT /_river/my_mysql_river/_meta
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/test",
        "user" : "",
        "password" : "",
        "sql" :  "select *, created as _id from orders",
        "index": "logs",
        "type": "software",
        "type_mapping": {
            "software": {
                "properties" : {
                    "software_name": { "type": "string", "index": "not_analyzed" }
                }
            }
        }
    }
}
```

Here are the logs with ES 1.5.0 and JDBC plugin 1.5.0.0

```
[2015-03-25 23:05:12,903][INFO ][river.jdbc.SimpleRiverMouth] creating index logs with settings {} and mappings {software={"software":{"properties":{"software_name":{"index":"not_analyzed","type":"string"}}}}}
[2015-03-25 23:05:12,903][INFO ][river.jdbc.BulkNodeClient] newIndex: settings = {}
[2015-03-25 23:05:12,903][INFO ][river.jdbc.BulkNodeClient] newIndex: type = software mappings = {"software":{"properties":{"software_name":{"index":"not_analyzed","type":"string"}}}}
[2015-03-25 23:05:12,914][INFO ][cluster.metadata         ] [Baron Blood] [logs] creating index, cause [api], templates [], shards [5]/[1], mappings [software]
[2015-03-25 23:05:12,939][INFO ][river.jdbc.BulkNodeClient] index logs created
```

**Comment by sstorie** [comment]
Your last mention about the 1.5 version of the plugin helped me figure this out...and of course it was on my end! I had two versions of this plugin in my elasticsearch folder, and that was causing these issues. As soon as I cleaned them up, and got the 1.5 version installed it works just like you described.

Sorry for raising the issue, but thank you so much for helping me figure this out.
