### ISSUE TITLE
standalone JDBC feeder doesn't work

### ISSUE THREAD

**Issue by jeffreyji666** [jprante/elasticsearch-river-jdbc#515]
my es version is 1.5.0 with river jdbc 1.5.0.0, and I run the following script:

> curl -XPUT 'localhost:9200/_river/my_jdbc_river/_meta' -d '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/forum",
        "user" : "root",
        "password" : "",
        "sql" : "select id as _id,id as topicId,title,body,created_at as createdAt,updated_at as updatedAt, 0 as replyCounts, 0 as starCounts, false as isDeleted from forum_topics"
    }
}'

it can load the mysql data into es successfully. but when I run the the following script:

>  #!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export ES_HOME=/opt/java/elasticsearch-1.5.0
curl -XDELETE 'http://localhost:9200/forum/topic'
echo 'forum topic index is deleted'
curl -XPUT 'http://localhost:9200/forum/topic'
echo 'recreate forum topic index'
curl -XPUT 'localhost:9200/forum/topic/_mapping' -d '{
 "topic": {
        "properties": {
            "topicId": {
                "type": "long",
                "store": "yes"
            },
            "title": {
                "type": "string",
                "index_analyzer": "index_ansj",
                "search_analyzer": "query_ansj",
                "store": "yes",
                "term_vector": "with_positions_offsets",
                "include_in_all": "true"
            },
            "body": {
                "type": "string",
                "index_analyzer": "index_ansj",
                "search_analyzer": "query_ansj",
                "store": "yes",
                "term_vector": "with_positions_offsets",
                "include_in_all": "true"
            },
            "createdAt": {
                "type" : "date",
                "format" : "dateOptionalTime"
            },
            "updatedAt": {
                "type" : "date",
                "format" : "dateOptionalTime"
            },
            "replyCounts": {
                "type": "integer",
                "store": "yes"
            },
            "starCounts": {
                "type": "integer",
                "store": "yes"
            },
            "isDeleted": {
                "type": "boolean",
                "index": "not_analyzed"
            }
        }
    }
}'

> echo '
{
    "elasticsearch" : {
         "cluster" : "es",
         "host" : "localhost",
         "port" : 9300
    },
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/forum",
        "user" : "root",
        "password" : "test",
        "sql" :  "select id as _id,id as topicId,title,body,created_at as createdAt,updated_at as updatedAt, 0 as replyCounts, 0 as starCounts, false as isDeleted from forum_topics",
        "index" : "forum",
        "type" : "topic"
      }
}
' | java \
    -cp "${DIR}/*" \
    org.xbib.elasticsearch.plugin.jdbc.feeder.Runner \
    org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder 

the log shows as follows:

> [2015-04-01 19:57:09,046][INFO ][cluster.metadata         ] [Alexander Goodwin Pierce] [[forum]] remove_mapping [[topic]]
{"acknowledged":true}forum topic index is deleted
[2015-04-01 19:57:09,073][INFO ][cluster.metadata         ] [Alexander Goodwin Pierce] [forum] create_mapping [topic]
{"acknowledged":true}Classpath: [file:/opt/java/elasticsearch-1.5.0/plugins/jdbc/, file:/opt/java/elasticsearch-1.5.0/plugins/jdbc/elasticsearch-river-jdbc-1.5.0.0.jar, file:/opt/java/elasticsearch-1.5.0/plugins/jdbc/jdbc-driver-csv-1.0.0.jar, file:/opt/java/elasticsearch-1.5.0/plugins/jdbc/mysql-connector-java-5.1.34.jar, file:/opt/java/elasticsearch-1.5.0/lib/antlr-runtime-3.5.jar, file:/opt/java/elasticsearch-1.5.0/lib/apache-log4j-extras-1.2.17.jar, file:/opt/java/elasticsearch-1.5.0/lib/asm-4.1.jar, file:/opt/java/elasticsearch-1.5.0/lib/asm-commons-4.1.jar, file:/opt/java/elasticsearch-1.5.0/lib/elasticsearch-1.5.0.jar, file:/opt/java/elasticsearch-1.5.0/lib/groovy-all-2.4.0.jar, file:/opt/java/elasticsearch-1.5.0/lib/jna-4.1.0.jar, file:/opt/java/elasticsearch-1.5.0/lib/jts-1.13.jar, file:/opt/java/elasticsearch-1.5.0/lib/log4j-1.2.17.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-analyzers-common-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-core-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-expressions-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-grouping-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-highlighter-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-join-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-memory-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-misc-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-queries-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-queryparser-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-sandbox-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-spatial-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/lucene-suggest-4.10.4.jar, file:/opt/java/elasticsearch-1.5.0/lib/spatial4j-0.4.1.jar]
log4j:WARN No appenders could be found for logger (JDBCFeeder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2015-04-01 19:57:11,082][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][0] updating refresh_interval from [1s] to [-1]
[2015-04-01 19:57:11,082][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][3] updating refresh_interval from [1s] to [-1]
[2015-04-01 19:57:11,082][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][1] updating refresh_interval from [1s] to [-1]
[2015-04-01 19:57:11,083][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][2] updating refresh_interval from [1s] to [-1]
[2015-04-01 19:57:11,083][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][4] updating refresh_interval from [1s] to [-1]
[2015-04-01 19:58:41,417][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][0] updating refresh_interval from [-1] to [1s]
[2015-04-01 19:58:41,418][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][3] updating refresh_interval from [-1] to [1s]
[2015-04-01 19:58:41,418][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][1] updating refresh_interval from [-1] to [1s]
[2015-04-01 19:58:41,418][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][2] updating refresh_interval from [-1] to [1s]
[2015-04-01 19:58:41,418][INFO ][index.shard              ] [Alexander Goodwin Pierce] [forum][4] updating refresh_interval from [-1] to [1s]
forum topic data is indexed

I didn't get any error message, please help me to solve this issue.

**Comment by jprante** [comment]
```
log4j:WARN No appenders could be found for logger (JDBCFeeder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
Can you add a `log4j.properties` file for logging?

**Comment by jeffreyji666** [comment]
I add the log4j.properties file in the plugins/jdbc directory and it shows as follows:
> 2015-04-01 21:08:46,035 ERROR [pool-3-thread-1] jdbc.SimpleRiverSource - while opening read connection: jdbc:mysql://localhost:3306/forum No suitable driver found for jdbc:mysql://localhost:3306/forum
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/forum
        at java.sql.DriverManager.getConnection(DriverManager.java:596)
        at java.sql.DriverManager.getConnection(DriverManager.java:187)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.getConnectionForReading(SimpleRiverSource.java:220)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.execute(SimpleRiverSource.java:393)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:332)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.fetch(SimpleRiverFlow.java:226)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.execute(SimpleRiverFlow.java:152)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.request(RiverPipeline.java:88)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:66)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

However, I have already put the mysql-connector-java-5.1.35-bin.jar file in the plugins/jdbc directory.

**Comment by jprante** [comment]
Please, fix the line

```
-cp "${DIR}/*"
```

with the correct classpath. An current example is here at the wiki https://github.com/jprante/elasticsearch-river-jdbc/wiki/JDBC-plugin-feeder-mode-as-an-alternative-to-the-deprecated-Elasticsearch-River-API

```
-cp "${ES_HOME}/lib/*:${ES_HOME}/plugins/jdbc/*" \
```

**Comment by jeffreyji666** [comment]
Thanks, that does work.
