### ISSUE TITLE
Add timestamp field for Logstash & Kibana Visualization

### ISSUE THREAD

**Issue by deusofnull** [jprante/elasticsearch-river-jdbc#519]
Hey all.  I am trying to have a method of visualizing data from a SQL server using the ELK stack.   I am pulling the output of a SP in SQL into Elasticsearch using this JDBC River.  

    curl -XPUT 'localhost:9200/_river/report_posting_ops/_meta' -d '{
        "type": "jdbc",
        "schedule": "0 0/15 1-23 ? * *",
        "jdbc": {
                "url": "jdbc:sqlserver://host.example.com:1433;databaseName=dbname",
                "locale": true,
                "user": "dbuser",
                "password": "password@123",
                "sql": [
                        {
                                "callable": true,
                                "statement": "EXEC [Report].[usp_dashboard_operation_posting_trend_15min]"
                        }
                       ],
                "index": "sql_posting_ops",
                "type": "sql_posting_trends"
                }
        }'

And it works great for pulling the SQL reports out of SQL.  
This is what the data looks like

    {
     "_index": "sql_posting_ops",
      "_type": "jt_sql_posting_trends",
      "_id": "AUyAmhp4CW0VqTsqp8uI",
      "_score": 1,
      "_source": {
         "posting_status": "pending_confirm",
         "day_name": "Friday",
         "day_timeinterval": "2015-04-03 00:45:00",
         "posting_count": 14,
          "average_posting_count": 14,
          "average_posting_day_count": 45
     }
}

The issue is that I would like to create a time-stamped field out of the returned data so that I can crate time-indexed searches / visualizations using Kibana.  This requires something akin to a logstash-event time-stamp or an event field logstash date-filtered time stamp.   I would want to use the "day_timeinterval" field to do this.  

Is there any way of using this JDBC river in order to add a timestamp that Kibana would recognize as valid?   Any help or ideas would be greatly appreciated.

**Comment by jprante** [comment]
You can configure ES date field mapping, like this

	#!/bin/sh

	/usr/local/mysql/bin/mysql -u root test <<EOT
	drop table test;
	create table test (
		id integer,
		d text
	);
	insert into test values (1, '2015-04-03 00:45:00');
	EOT

	curl -XDELETE 'localhost:9200/_river/my_test_river/'

	curl -XDELETE 'localhost:9200/mytest'

	curl -XPOST 'localhost:9200/_river/my_test_river/_meta' -d '
	{
		"type" : "jdbc",
		"jdbc" : {
			"url" : "jdbc:mysql://localhost:3306/test",
			"user" : "",
			"password" : "",
			"sql" : "select *,id as _id from test",
			"index" : "mytest",
			"type" : "mydocs",
			"index_settings" : { },
			"type_mapping" : {
				  "mydocs" : {
					  "properties" : {
						   "d" : { 
								"type" : "date",
								"format" : "yyyy-MM-dd HH:mm:ss"
						   }
					  }
				  }
			}
		}
	}
	'

	echo "sleeping while river should run..."

	sleep 5

	curl -XGET 'localhost:9200/mytest/_mapping?pretty'

	curl -XPOST 'localhost:9200/mytest/_search?pretty' -d '
	{
		   "query": {
			  "match_all": {
			   }
		   }
	}'

	curl -XDELETE 'localhost:9200/_river/my_test_river/'

**Comment by deusofnull** [comment]
Much obliged! This makes everything much clearer!   I have these field mappings for my sql_postinog_ops ES index now and they work great!

          "day_timeinterval" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss"
          },

I swear I knew I was doing something against the grain with my prior course.  Thank you for your quick response!

**Comment by deusofnull** [comment]
Hey there.  Sorry to re-open this issue, but I am seeing something very strange with my data now.  

It appears that the datetime is being filtered int a valid time interval, but it is 4 hours slow in Kibana.  Take a look here at one kibana event:

![image](https://cloud.githubusercontent.com/assets/3485446/7011448/342c6dca-dc77-11e4-9180-bc94cdf11818.png)

Any thoughts on why that could be happening?

**Comment by jprante** [comment]
Maybe you have to adjust the time zone with the parameter `timezone`, I do not know what time zone you use in the DB.

**Comment by deusofnull** [comment]
We would be using East Cost Standard -5GMT,  Should the stored procedure be altered to include that information, an then we can parse it with the timezone param, as you say.

I do not see anything about the timezone parameter on this documentation for field mapping though
http://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-date-format.html
It is the doc I have been referencing for the different kinds of dates as well as for the JODA format.

Can I just use the date math which they show near the top? 

IE: 
```
      "day_timeinterval" : {
        "type" : "date",
        "format" : "yyyy-MM-dd HH:mm:ss  + 04h"
      },
```

Thank you so much for all your help by the way :)

**Comment by jprante** [comment]
I must correct myself, `timezone` parameter is for SQL datetime columns only.

Elasticsearch uses UTC timestamps. The stored procedure should be altered to UTC (no timezone) and everything will be fine.

**Comment by deusofnull** [comment]
So instead of having a timestamp including a timezone such as 
```
timestamp: 01/01/2015 10:00:00 -05:00
```
I should have  the SP write time stamp in  UTC? Would the addition of '-05:00' not work?

**Comment by deusofnull** [comment]
As I'd imagine it, the JODA format for the time stamp added datetime would look like 
```
MM/dd/yyyy HH:mm:ss Z
```

**Comment by jprante** [comment]
If you can not set UTC time, you have to specify a timezone, yes. Joda `Z` is for timezone without colon, `ZZ` is for timezone with colon.

**Comment by deusofnull** [comment]
Ok, thats great. I think I'll have the SP edited to include a zz timezone.

**Comment by deusofnull** [comment]
Hey @jprante 

I have made some changes to my stored procedure, or rather the DBA guys did, and am now having a new issue.

The new timestamp format coming out of SQL looks like this: 
```2015-03-08 02:00:00 EST```

As per the Joda documentation, I assumed that the 'z' character would match this pattern:
 ```z: time zone:                   text :         Pacific Standard Time; PST````

However, when I use a field mapping for my timestamp field like this:
```          "day_timeinterval" : {
            "type" : "date",
            "format": "yyyy-MM-dd HH:mm:ss z"
          }, ```

I get a pretty nasty "Illegal instant" Exception:
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [day_timeinterval]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [2015-03-08 02:15:00 EST], tried both date format [yyyy-MM-dd HH:mm:ss z], and timestamp number with locale []
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:621)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:549)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:235)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
        ... 12 more
Caused by: org.elasticsearch.common.joda.time.IllegalInstantException: Cannot parse "2015-03-08 02:15:00 EST": Illegal instant due to time zone offset transition (America/New_York)
        at org.elasticsearch.common.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390)
        at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:749)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:615)```

Do you have any suggestions for how to handle this?  Would the ZZ / Z pattern solve this issue if the  stored procedure were changed?

**Comment by jprante** [comment]
You are referencing a datetime that does not exist due to daylight savings time changes.
Valid is `2015-03-08 01:59:59 EST`, the next second is `2015-03-08 03:00:00 EST`
